carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),

]

greatcart/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', views.home, name='home'), 
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.store, name='store'), 
    path('<slug:category_slug>/', views.store, name='products_by_category'), 
    path('<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
   
    path('submit_review/<int:product_id>', views.submit_review, name='submit_review'),
]

store/models.py
from django.db import models
from django.db.models import Avg
from django.urls import reverse
from category.models import Category
from accounts.models import Account
# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def averageReview(self):
        rewiews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg =0
        if rewiews['average'] is not None:
            avg = float(rewiews['average'])
        
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Avg('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
            return count


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)



VARIATION_CATEGORY_CHOICE = (
    ('color', 'color'),
    ('size', 'size'),
)
        
class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=VARIATION_CATEGORY_CHOICE)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value
    
    # def __unicode__(self):
    #     return self.product
    


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)


class ProductGalery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms
from django.forms import fields
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from typing import ItemsView
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from store.models import Product, Variation
from django.shortcuts import get_object_or_404, redirect, render
from . models import Cart, CartItem

from django.contrib.auth.decorators import login_required


from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user

    product = Product.objects.get(id=product_id)

    #if user atuentikated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass



        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()

        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
        
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)


            if product_variation in ex_var_list:
                #Increase
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id )
                item.quantity += 1
                item.save()
                
            else:
                # create new
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation)>0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                # cart_item.quantity +=1 
                item.save()
        else:

            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                user=current_user,
            )
            if len(product_variation)>0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        #return HttpResponse(cart_item.quantity)
        return redirect('cart')
    # is user not autehticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()


        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()

        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            #existing variations > database
            #current variations > product avriatin
            # item id   >database

            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)


            print(ex_var_list)

            if product_variation in ex_var_list:
                #Increase
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id )
                item.quantity += 1
                item.save()
                
            else:
                # create new
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation)>0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                # cart_item.quantity +=1 
                item.save()
        else:

            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                cart = cart,
            )
            if len(product_variation)>0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        #return HttpResponse(cart_item.quantity)
        return redirect('cart')


def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity>1:
            cart_item.quantity-=1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')





def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2*total)/100
        grand_total = total+tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total':total,
        'quantity':quantity,
        'cart_items':cart_items,
        'tax':tax,
        'grand_total':grand_total,
    }


    return render(request, 'store/cart.html', context)



@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2*total)/100
        grand_total = total+tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total':total,
        'quantity':quantity,
        'cart_items':cart_items,
        'tax':tax,
        'grand_total':grand_total,
    }


    return render(request, 'store/checkout.html', context)

store/views.py
from typing import OrderedDict
from django.contrib import messages
from store.forms import ReviewForm
from django.core import paginator
from django.http import HttpResponse
from carts.models import CartItem
from django.shortcuts import get_object_or_404, redirect, render
from store.models import Product, ProductGalery, ReviewRating
from category.models import Category
from carts.views import _cart_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from orders.models import OrderProduct

# Create your views here.
def store(request,category_slug=None):
    categories = None 
    products=None

    if category_slug !=None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category = categories, is_available=True)
        #Paginator kodu
        paginator = Paginator(products, 6)
        page = request.GET.get('page') #linkdegi ?page=
        paged_products = paginator.get_page(page)

        #product sayi
        product_count = products.count()
        
        
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        #Paginator kodu
        paginator = Paginator(products, 9)
        page = request.GET.get('page') #linkdegi ?page=
        paged_products = paginator.get_page(page)

        #product sayi
        product_count = products.count()


    context = {
        'products':paged_products,
        'product_count':product_count,
        'paged_products':paged_products
        
    }
    return render(request, 'store/store.html', context)


# def product_detail(request, category_slug, product_slug):
#     category = get_object_or_404(Category, slug = category_slug)
#     single_product = get_object_or_404(Product, slug = product_slug, category_id=category.id)
    
#     context=dict(
#     single_product=single_product)
#     return render(request, 'store/product_detail.html',context)


def product_detail(request, category_slug, product_slug):

    
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product = single_product).exists()


        # return HttpResponse(in_cart)
        # exit()
    except Exception as e:
        raise e
    ################################
    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user = request.user, product_id = single_product.id).exists()

        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    #######################################
    #rewiewsi listelemek
    reviews = ReviewRating.objects.filter(product_id = single_product.id, status=True)

    product_galery = ProductGalery.objects.filter(product_id = single_product.id)
    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct': orderproduct,
        'reviews':reviews,
        'product_galery': product_galery,
    }
    return render(request, 'store/product_detail.html',context)



def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')  
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.rating = form.cleaned_data['rating']
                data.subject = form.cleaned_data['subject']
                data.review = form.cleaned_data['review']
                data.product_id = product_id
                data.user_id = request.user.id
                data.ip = request.META.get('REMOTE_ADDR')
                data.save()
                messages.success(request, 'Thank you! Your review has been updated.')
                return redirect(url)
            
        

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->

{% if not cart_items %}
<h2> Your Shopping Cart is Empty </h2>
<hr>
<div>
	<a href="{% url 'store' %}" class="btn btn-primary">Continue Shopping</a>
</div>
{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>

{% for cart_item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{cart_item.product.images.url}}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
				<p class="text-muted small">
			
				{% if cart_item.variations.all %}
					{% for item  in cart_item.variations.all %}
					{{item.variation_category | capfirst}} : {{item.variation_value | capfirst}}
					{% endfor %}
				{% endif %}
				
				
				</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.//  -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href ="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{cart_item.quantity}}">
							<div class="input-group-append">
							<form action="{% url 'add_cart' cart_item.product.id %}"  method="POST">
								{% csrf_token %}
								{% for item in cart_item.variations.all %}
								<input type ="hidden" name="{{item.variation_category | lower }}" value="{{item.variation_value | capfirst }}">
								{% endfor %}
								<button  class="btn btn-light" type="Submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
							</form>
						</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">${{cart_item.sub_total}}</var> 
			<small class="text-muted"> ${{cart_item.product.price}} each </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Deqiq silmekisteyirsen?')" class="btn btn-danger"> Remove</a>
	</td>
</tr>



{% endfor %}




</tbody>
</table>



</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">{{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{tax}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->

{% endif %}

<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}

templates/store/product_detail.html
{% extends 'base.html' %}

{% block content %}

<section class="section-content padding-y bg">
	<div class="container">

		<!-- ============================ COMPONENT 1 ================================= -->
		<div class="card">
			<div class="row no-gutters">
				<aside class="col-md-6">
					<article class="gallery-wrap">
						<div class="img-big-wrap mainImage">
							<a href="#"><img src="{{single_product.images.url}}"></a>
						</div> <!-- img-big-wrap.// -->
					</article> <!-- gallery-wrap .end// -->
					<ul class="thumb">
						<li>
							{% for i in product_galery %}
							<a href="{{i.image.url}}" target="mainImage"> <img src="{{i.image.url}}" alt="Product Image"></a>
							{% endfor %}
						</li>
					</ul>
				</aside>



				<main class="col-md-6 border-left">
					<!---->
					<form action="{% url 'add_cart' single_product.id %}" method="post">
						{% csrf_token %}
						<article class="content-body">

							<h2 class="title">{{single_product.product_name}}</h2>

<br>
				<header class="section-heading">
					<span> Average Review: {{single_product.averageReview}} </span>
							<div class="rating-star">
								<span>
									<i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
								</span>
								<span>{{single_product.countReview}} Reviews </span>
							</div>
							

				</header>

<br>

							<div class="mb-3">
								<var class="price h4">{{single_product.price}}</var>
							</div>

							<p>{{single_product.description}}</p>


							<hr>
							<div class="row">
								<div class="item-option-select">
									<h6>Choose Color</h6>
									<select name="color" class="form-control" required>
										<option value="" disabled selected>Choose color</option>
										{% for i in single_product.variation_set.colors %}
										<option value="{{i.variation_value | lower }}">{{i.variation_value| capfirst}}
										</option>
										{% endfor %}
									</select>


									<!-- <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
										<label class="btn btn-light">
											<input type="radio" name="radio_color"> Silver
										</label>
										<label class="btn btn-light">
											<input type="radio" name="radio_color"> Gray
										</label>
										<label class="btn btn-light active">
											<input type="radio" name="radio_color checked"> Gold
										</label>
										<label class="btn btn-light">
											<input type="radio" name="radio_color"> Black
										</label>
									</div> -->
								</div>
							</div> <!-- row.// -->

							<div class="row">
								<div class="item-option-select">
									<h6>Select Size</h6>
									<select name="size" class="form-control">
										<option value="" disabled selected>Choose size</option>
										{% for i in single_product.variation_set.sizes %}
										<option value="{{i.variation_value | lower}}">{{i.variation_value | capfirst}}
										</option>
										{% endfor %}
									</select>
									</select>


									<!-- <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
										<label class="btn btn-light">
											<input type="radio" name="radio_color"> S
										</label>
										<label class="btn btn-light active">
											<input type="radio" name="radio_color" checked> M
										</label>
										<label class="btn btn-light">
											<input type="radio" name="radio_color"> L
										</label>
										<label class="btn btn-light">
											<input type="radio" name="radio_color"> XL
										</label>
									</div> -->
								</div>
							</div> <!-- row.// -->
							<hr>

							{% if single_product.stock <= 0 %}
							Stokta yoktur
							{% else %}
							{% comment %}
							{% if in_cart %}
							<a href="#" class="btn  btn-success"> <span class="text">Added to cart</span> <i
									class="fas fa-check"></i> </a>
							<a href="{% url 'cart'  %}" class="btn  btn-outline-primary"> <span class="text">View
									Cart</span> <i class="fas fa-eye"></i> </a>
							{% else %} {% endcomment %}
							<button type='submit' class="btn  btn-primary"> <span class="text">Add to cart</span> <i
									class="fas fa-shopping-cart"></i> </button>

							{% comment %} {% endif %} {% endcomment %}
							{% endif %}



						</article> <!-- product-info-aside .// -->
					</form>
					<!---->
				</main> <!-- col.// -->
			</div> <!-- row.// -->
		</div> <!-- card.// -->
		<!-- ============================ COMPONENT 1 END .// ================================= -->

		<br>

		<div class="row">
			<div class="col-md-9">



				<form action="{% url 'submit_review' single_product.id %}" method="POST">

					{% csrf_token %}
					<h5> Write Your Review </h5>
					
					<div>
						<!--Rating star  -->
						<label for="">How do you rate this product</label>
						<br>
						<div class="rate" >
							<input type="radio" name="rating" id="rating10" value="5" required> <label for="rating10" title="5"></label>
							<input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" class="half" title="4.5"></label>
							<input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
							<input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
							<input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
							<input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
							<input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
							<input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
							<input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
							<input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
						</div>
						<br>
						Review Title:
						<input type="text" class="form-control" name="subject">
						<br>
						Review:
						<textarea name="review" class="form-control" rows="4"></textarea>
						<br>
						{% if request.user.is_authenticated %}

							{% if orderproduct %}
							<input type="submit"  class="btn btn-primary"  value="Submit Review">
							{% else %}
							You must puschace for review yo this product
							{% endif %}
						
						{% else %}
						<h4>you be logged in to post a rewiev<h/4>
							<span><a href="{% url 'login' %}">Login Now</a></span>
						{% endif %}
						
						<br>
					</div>
					<br>
				{% include 'includes/alerts.html' %}
				</form>

<br>
				<header class="section-heading">
					<h3>Customer Reviews </h3>
					<span> Average Review: {{single_product.averageReview}} </span>
												<div class="rating-star">
								<span>
									<i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
								</span>
							</div>
							<span>{{single_product.countReview}} Reviews </span>

				</header>

<br>
				{% for review in reviews %}
				<article class="box mb-3">
					<div class="icontext w-100">
						<img src="{{review.user.image.url}}" class="img-xs icon rounded-circle">

						<div class="text">
							<span class="date text-muted float-md-right">{{review.created_at}} </span>
							<h6 class="mb-1">{{review.user.full_name}}</h6>
							
							{{review.rating}}
							<div class="rating-star">
								<span>
									<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
								</span>
							</div>

						</div>
					</div> 
					<br><!-- icontext.// -->
					<div class="mt-3">
					<h6>{{review.subject}}</h6>
					<hr>
						<p>
							{{review.review}}
						</p>
					</div>
				</article>
				{% endfor %}


			</div> <!-- col.// -->
		</div> <!-- row.// -->


	</div> <!-- container .//  -->
</section>
<!-- ======


{% endblock content %}